### ISSUE TITLE
Extend vector2vector operations to matrix2matrix

### ISSUE THREAD

**Issue by r9y9** [r9y9/pysptk#49]
We often do frame-by-frame processing. For example, if we want to compute mel-cepstrum for each frame, currently we need to write something lke:

```py
frames = ... # shape: (num_frames, frame_len)
mc = np.apply_along_axis(pysptk.mcep, 1, frames, order=24, alpha=0.41)
```

I've been thinking recently it would be useful if we can simply write:

```py
mc = pysptk.mcep(frames, order=24, alpha=0.41)
```

**Comment by wuaalb** [comment]
This would be very nice!

I initially expected pysptk to function like that, as SPTK's command line interface also performs matrix-wise operations.

Related to this, I sometimes find the relationship between pysptk's API and SPTK's CLI to be non-trivial. This is mainly because pysptk wraps "inner" functions like _mgc2sp.c, rather than "outer" functions like mgc2sp.c (which correspond to SPTK's CLI and documentation). Sometimes I have to check both SPTK's original source code as well as pysptk to be sure things do what I expect. Anyways, this is a minor (documentation) issue.

**Comment by r9y9** [comment]
Yes, pysptk's API is based on the inner functions, so the functionalities are not exactly same as SPTK's CLI (though I tried to keep consistent as possible). Since it's hard to keep exactly consistent with the SPTK's CLI, I want to address this as a doc issue for the first step. I will improve the docs later.
